# Based on draft-release.yml from https://github.com/limbonaut/limbo_console because i do not know yaml 😭

name: Draft Release
on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize version
        shell: bash
        run: |
          echo "VERSION=$( (git describe --tags --exact-match HEAD || git rev-parse --short HEAD) | sed 's/\(.*\)-\(.*\)/\1.\2/g' )" >> "$GITHUB_ENV"

      - name: Create artifact
        shell: bash
        run: |
          mkdir out/
          git archive --prefix="addons/command-terminal/" --output="out/command_terminal_${VERSION}.zip" ${{ github.ref }}

      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts: "out/command_terminal_${{ env.VERSION }}.zip"